# -*- coding: utf-8 -*-
"""Sustainable

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bF9tsYmoH-l9XN4Mf7JT9-fc8UFm_AVo
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib import rcParams

# ── Page config ──────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="ESG Portfolio Optimizer",
    page_icon="🌱",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Custom CSS ────────────────────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=DM+Sans:wght@300;400;500;600&display=swap');

html, body, [class*="css"] {
    font-family: 'DM Sans', sans-serif;
}

/* Background */
.stApp {
    background: linear-gradient(135deg, #0a0f1e 0%, #0d1a2e 50%, #071020 100%);
    color: #e8edf5;
}

/* Sidebar */
section[data-testid="stSidebar"] {
    background: linear-gradient(180deg, #0d1f35 0%, #091829 100%);
    border-right: 1px solid rgba(100, 200, 150, 0.15);
}
section[data-testid="stSidebar"] .stMarkdown p,
section[data-testid="stSidebar"] label,
section[data-testid="stSidebar"] .stSelectbox label,
section[data-testid="stSidebar"] .stRadio label {
    color: #b8cce0 !important;
}

/* Hero header */
.hero-header {
    text-align: center;
    padding: 2.5rem 1rem 1.5rem;
    border-bottom: 1px solid rgba(100, 200, 150, 0.2);
    margin-bottom: 2rem;
}
.hero-title {
    font-family: 'DM Serif Display', serif;
    font-size: 3rem;
    background: linear-gradient(135deg, #52e89b 0%, #38b2ac 50%, #4299e1 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    letter-spacing: -0.5px;
    margin: 0;
}
.hero-subtitle {
    color: #7a9bbf;
    font-size: 1.05rem;
    font-weight: 300;
    margin-top: 0.4rem;
    letter-spacing: 0.5px;
}

/* Section headers */
.section-header {
    font-family: 'DM Serif Display', serif;
    font-size: 1.4rem;
    color: #52e89b;
    margin-bottom: 0.2rem;
    margin-top: 0.5rem;
}
.section-divider {
    border: none;
    border-top: 1px solid rgba(100, 200, 150, 0.2);
    margin: 1.5rem 0;
}

/* Metric cards */
.metric-card {
    background: linear-gradient(135deg, rgba(20,40,65,0.9) 0%, rgba(15,30,50,0.95) 100%);
    border: 1px solid rgba(100, 200, 150, 0.25);
    border-radius: 12px;
    padding: 1.2rem 1.4rem;
    margin-bottom: 0.8rem;
    position: relative;
    overflow: hidden;
}
.metric-card::before {
    content: '';
    position: absolute;
    top: 0; left: 0; right: 0;
    height: 2px;
    background: linear-gradient(90deg, #52e89b, #4299e1);
}
.metric-label {
    font-size: 0.72rem;
    text-transform: uppercase;
    letter-spacing: 1.5px;
    color: #7a9bbf;
    margin-bottom: 0.3rem;
}
.metric-value {
    font-family: 'DM Serif Display', serif;
    font-size: 1.9rem;
    color: #e8f5f0;
    line-height: 1.1;
}
.metric-sub {
    font-size: 0.78rem;
    color: #52e89b;
    margin-top: 0.2rem;
}

/* Portfolio card */
.portfolio-card {
    background: rgba(15, 30, 50, 0.8);
    border: 1px solid rgba(100, 200, 150, 0.2);
    border-radius: 14px;
    padding: 1.6rem;
    margin-bottom: 1rem;
}
.portfolio-title {
    font-family: 'DM Serif Display', serif;
    font-size: 1.15rem;
    color: #52e89b;
    margin-bottom: 1rem;
    display: flex;
    align-items: center;
    gap: 0.5rem;
}

/* Weight bar */
.weight-bar-wrap { margin-bottom: 0.6rem; }
.weight-bar-label {
    font-size: 0.8rem;
    color: #b8cce0;
    margin-bottom: 2px;
    display: flex;
    justify-content: space-between;
}
.weight-bar-track {
    background: rgba(255,255,255,0.06);
    border-radius: 99px;
    height: 10px;
    overflow: hidden;
}
.weight-bar-fill {
    height: 100%;
    border-radius: 99px;
    transition: width 0.6s ease;
}

/* Sliders & inputs theming */
.stSlider > div > div > div > div { background: #52e89b !important; }
.stSelectbox > div { background: rgba(20,40,65,0.9) !important; border-color: rgba(100,200,150,0.3) !important; }
.stRadio > label { color: #b8cce0 !important; }
.stNumberInput input { background: rgba(20,40,65,0.9) !important; color: #e8edf5 !important; border-color: rgba(100,200,150,0.3) !important; }
div[data-baseweb="select"] { background: rgba(20,40,65,0.9) !important; }

/* Tabs */
.stTabs [data-baseweb="tab-list"] { background: rgba(10,20,35,0.6); border-radius: 10px; }
.stTabs [data-baseweb="tab"] { color: #7a9bbf; }
.stTabs [aria-selected="true"] { color: #52e89b !important; background: rgba(82,232,155,0.1) !important; }

/* Expander */
.streamlit-expanderHeader { color: #52e89b !important; }

/* Info boxes */
.info-box {
    background: rgba(66, 153, 225, 0.08);
    border-left: 3px solid #4299e1;
    border-radius: 0 8px 8px 0;
    padding: 0.8rem 1rem;
    margin: 0.5rem 0;
    font-size: 0.88rem;
    color: #b8cce0;
}
.success-box {
    background: rgba(82, 232, 155, 0.08);
    border-left: 3px solid #52e89b;
    border-radius: 0 8px 8px 0;
    padding: 0.8rem 1rem;
    margin: 0.5rem 0;
    font-size: 0.88rem;
    color: #b8cce0;
}
</style>
""", unsafe_allow_html=True)

# ── Helper functions ──────────────────────────────────────────────────────────

def convert_to_100(score, agency):
    agency = agency.lower()
    if agency == "sustainalytics":
        score = float(score)
        if score >= 50:
            return 0.0
        return max(0.0, min(100.0, 100 - (score / 50) * 100))
    elif agency == "msci":
        msci_map = {"ccc": 0, "b": 16.7, "bb": 33.4, "bbb": 50.1, "a": 66.8, "aa": 83.5, "aaa": 100.0}
        return msci_map[str(score).lower()]
    elif agency == "refinitiv":
        refinitiv_map = {0: 0.0, 1: 10.0, 2: 25.0, 3: 50.0, 4: 75.0, 5: 95.0}
        return refinitiv_map[int(float(score))]
    elif agency == "s&p":
        return max(0.0, min(100.0, float(score)))

def portfolio_return(w1, r1, r2):
    return w1 * r1 + (1 - w1) * r2

def portfolio_sd(w1, sd1, sd2, rho):
    return np.sqrt(w1**2 * sd1**2 + (1-w1)**2 * sd2**2 + 2*rho*w1*(1-w1)*sd1*sd2)

def portfolio_esg(w1, esg1, esg2):
    return w1 * esg1 + (1 - w1) * esg2

def esg_color(score):
    if score >= 70: return "#52e89b"
    if score >= 45: return "#f6c90e"
    return "#f87171"

def esg_label(score):
    if score >= 70: return "Strong"
    if score >= 45: return "Moderate"
    return "Weak"

# ── Matplotlib style ──────────────────────────────────────────────────────────
def apply_dark_style():
    rcParams.update({
        'figure.facecolor': '#0d1a2e',
        'axes.facecolor': '#0a1525',
        'axes.edgecolor': '#1e3555',
        'axes.labelcolor': '#b8cce0',
        'xtick.color': '#7a9bbf',
        'ytick.color': '#7a9bbf',
        'text.color': '#e8edf5',
        'grid.color': '#1a3050',
        'grid.linestyle': '--',
        'grid.alpha': 0.4,
        'legend.facecolor': '#0d1a2e',
        'legend.edgecolor': '#2a4a70',
        'legend.labelcolor': '#b8cce0',
        'font.family': 'sans-serif',
    })

# ─────────────────────────────────────────────────────────────────────────────
# HERO
# ─────────────────────────────────────────────────────────────────────────────
st.markdown("""
<div class="hero-header">
  <p class="hero-title">🌱 ESG Portfolio Optimizer</p>
  <p class="hero-subtitle">Build a personalised portfolio aligned with your financial goals & sustainability values</p>
</div>
""", unsafe_allow_html=True)

# ─────────────────────────────────────────────────────────────────────────────
# SIDEBAR – ALL INPUTS
# ─────────────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("### ⚙️ Portfolio Settings")
    st.markdown("<hr style='border-color:rgba(100,200,150,0.2);margin:0.5rem 0 1rem'>", unsafe_allow_html=True)

    # ── ESG input method ─────────────────────────────────────────────────────
    st.markdown("**ESG Score Input Method**")
    esg_method = st.radio(
        "How would you like to enter ESG data?",
        ["Overall ESG score", "Separate E, S, G scores"],
        label_visibility="collapsed"
    )
    use_separate = (esg_method == "Separate E, S, G scores")

    pillar_weights = (33.33, 33.33, 33.34)
    if use_separate:
        with st.expander("🔧 Pillar weights", expanded=False):
            w_e = st.slider("Environmental (%)", 0, 100, 33)
            w_s = st.slider("Social (%)", 0, 100, 33)
            w_g = st.slider("Governance (%)", 0, 100, 34)
            total_w = w_e + w_s + w_g
            if abs(total_w - 100) > 0.5:
                st.error(f"Weights sum to {total_w}% — must equal 100%")
            else:
                pillar_weights = (w_e, w_s, w_g)

    st.markdown("<hr style='border-color:rgba(100,200,150,0.15);'>", unsafe_allow_html=True)

    # ── Asset names ──────────────────────────────────────────────────────────
    st.markdown("**Asset Names**")
    a1 = st.text_input("Asset 1 name", value="Apple (AAPL)")
    a2 = st.text_input("Asset 2 name", value="Tesla (TSLA)")

    st.markdown("<hr style='border-color:rgba(100,200,150,0.15);'>", unsafe_allow_html=True)

    # ── Financial parameters ─────────────────────────────────────────────────
    st.markdown(f"**{a1} – Financials**")
    r1_pct = st.slider(f"Expected return (%)", -20.0, 50.0, 8.0, 0.1, key="r1")
    sd1_pct = st.slider(f"Volatility / SD (%)", 0.1, 80.0, 22.0, 0.1, key="sd1")

    st.markdown(f"**{a2} – Financials**")
    r2_pct = st.slider(f"Expected return (%)", -20.0, 50.0, 12.0, 0.1, key="r2")
    sd2_pct = st.slider(f"Volatility / SD (%)", 0.1, 80.0, 38.0, 0.1, key="sd2")

    st.markdown("<hr style='border-color:rgba(100,200,150,0.15);'>", unsafe_allow_html=True)

    # ── Market assumptions ───────────────────────────────────────────────────
    st.markdown("**Market Assumptions**")
    rho = st.slider("Correlation (ρ)", -1.0, 1.0, 0.3, 0.01)
    rf_pct = st.slider("Risk-free rate (%)", 0.0, 10.0, 4.5, 0.1)

    st.markdown("<hr style='border-color:rgba(100,200,150,0.15);'>", unsafe_allow_html=True)

    # ── Risk preference ──────────────────────────────────────────────────────
    st.markdown("**Risk Preference (γ)**")
    gamma_mode = st.radio("Gamma input", ["Use questionnaire", "Enter manually"], label_visibility="collapsed")
    if gamma_mode == "Enter manually":
        gamma = st.slider("Gamma (γ)", -10.0, 10.0, 2.0, 0.5)
        st.caption("Positive = risk-averse · 0 = neutral · Negative = risk-loving")
    else:
        gamma = None  # will be set in questionnaire section

    st.markdown("<hr style='border-color:rgba(100,200,150,0.15);'>", unsafe_allow_html=True)

    # ── ESG preference ───────────────────────────────────────────────────────
    st.markdown("**ESG Preference (λ)**")
    lambda_choice = st.radio(
        "ESG willingness",
        [
            "0.0 – No ESG preference",
            "0.25 – Small trade-off",
            "0.75 – Moderate trade-off",
            "1.0 – Strong ESG alignment",
        ],
        index=1,
    )
    lambda_esg = float(lambda_choice.split("–")[0].strip())

# ─────────────────────────────────────────────────────────────────────────────
# MAIN – QUESTIONNAIRE (if needed) + ESG SCORES
# ─────────────────────────────────────────────────────────────────────────────

tabs = st.tabs(["📋 Inputs", "📊 Results & Charts"])

# ═══════════════════════════════════════════════════════
# TAB 1 – INPUTS
# ═══════════════════════════════════════════════════════
with tabs[0]:

    col_left, col_right = st.columns([1, 1], gap="large")

    # ── Risk questionnaire ───────────────────────────────────────────────────
    with col_left:
        st.markdown('<p class="section-header">🎯 Risk Profile</p>', unsafe_allow_html=True)

        if gamma_mode == "Use questionnaire":
            st.markdown('<div class="info-box">Answer 5 quick questions to determine your risk tolerance (γ).</div>', unsafe_allow_html=True)

            q_answers = []

            q_labels = [
                ("Q1 – General attitude", "How would you describe your general attitude towards investment risk?",
                 ["1 – I avoid risk wherever possible",
                  "2 – I prefer low-risk, steady options",
                  "3 – Comfortable with moderate risk",
                  "4 – Willing to take on risk for higher returns",
                  "5 – I actively seek high-risk, high-reward"]),
                ("Q2 – Safe vs. growth", '"I prefer an investment that grows slowly but steadily, even if it means lower returns."',
                 ["1 – Strongly agree", "2 – Tend to agree", "3 – In between",
                  "4 – Tend to disagree", "5 – Strongly disagree"]),
                ("Q3 – Reaction to loss", "Your portfolio drops 20% in 3 months. What is your most likely reaction?",
                 ["1 – Sell everything immediately",
                  "2 – Sell some to reduce exposure",
                  "3 – Do nothing, wait for recovery",
                  "4 – Review but stay the course",
                  "5 – Buy more – it's an opportunity"]),
                ("Q4 – High-risk allocation", "How much would you place in a high-risk, high-reward investment?",
                 ["1 – Very little, if any", "2 – Less than a quarter",
                  "3 – Around half", "4 – More than half", "5 – All of it"]),
                ("Q5 – Certain vs. uncertain gain", '"I would always prefer a small guaranteed return over a larger uncertain one."',
                 ["1 – Strongly agree", "2 – Tend to agree", "3 – In between",
                  "4 – Tend to disagree", "5 – Strongly disagree"]),
            ]

            for i, (label, question, options) in enumerate(q_labels):
                with st.expander(label, expanded=(i == 0)):
                    ans = st.radio(question, options, key=f"q{i}", label_visibility="visible")
                    q_answers.append(int(ans[0]))

            if len(q_answers) == 5:
                avg = sum(q_answers) / 5
                if avg <= 1.5:   gamma, risk_label = 8,  "Very Cautious"
                elif avg <= 2.3: gamma, risk_label = 4,  "Cautious"
                elif avg <= 3.2: gamma, risk_label = 0,  "Moderate / Risk-Neutral"
                elif avg <= 4.1: gamma, risk_label = -4, "Adventurous"
                else:            gamma, risk_label = -8, "Very Adventurous / Risk-Loving"

                color = "#52e89b" if gamma > 0 else ("#f6c90e" if gamma == 0 else "#f87171")
                st.markdown(f"""
                <div class="metric-card" style="margin-top:1rem;">
                  <div class="metric-label">Your Risk Profile</div>
                  <div class="metric-value" style="color:{color};">{risk_label}</div>
                  <div class="metric-sub">γ = {gamma}</div>
                </div>""", unsafe_allow_html=True)
        else:
            st.markdown(f"""
            <div class="metric-card">
              <div class="metric-label">Manual Gamma</div>
              <div class="metric-value">{gamma}</div>
              <div class="metric-sub">{'Risk-Averse' if gamma > 0 else ('Risk-Neutral' if gamma == 0 else 'Risk-Loving')}</div>
            </div>""", unsafe_allow_html=True)

    # ── ESG scores ───────────────────────────────────────────────────────────
    with col_right:
        st.markdown('<p class="section-header">🌿 ESG Scores</p>', unsafe_allow_html=True)

        AGENCY_OPTIONS = ["Sustainalytics", "MSCI", "Refinitiv (LSEG)", "S&P Dow Jones"]
        MSCI_RATINGS = ["CCC", "B", "BB", "BBB", "A", "AA", "AAA"]
        REFINITIV_SCORES = [0, 1, 2, 3, 4, 5]

        def esg_input_widget(asset_name, key_prefix, separate):
            st.markdown(f"**{asset_name}**")
            agency_raw = st.selectbox("Rating agency", AGENCY_OPTIONS, key=f"{key_prefix}_agency")
            agency = agency_raw.lower().replace(" (lseg)", "").replace("s&p dow jones", "s&p")

            if not separate:
                score_100 = _score_widget(agency, key_prefix, "Overall ESG")
                return score_100 / 100, score_100
            else:
                we, ws, wg = pillar_weights
                e = _score_widget(agency, key_prefix + "_e", "Environmental")
                s = _score_widget(agency, key_prefix + "_s", "Social")
                g = _score_widget(agency, key_prefix + "_g", "Governance")
                overall = (we/100)*e + (ws/100)*s + (wg/100)*g
                c1, c2, c3 = st.columns(3)
                c1.metric("E", f"{e:.0f}")
                c2.metric("S", f"{s:.0f}")
                c3.metric("G", f"{g:.0f}")
                return overall / 100, overall

        def _score_widget(agency, key, label):
            if agency == "msci":
                raw = st.select_slider(f"{label} (MSCI)", MSCI_RATINGS, value="BBB", key=key)
                return convert_to_100(raw, "msci")
            elif agency == "refinitiv":
                raw = st.select_slider(f"{label} (Refinitiv 0–5)", REFINITIV_SCORES, value=3, key=key)
                return convert_to_100(raw, "refinitiv")
            elif agency == "sustainalytics":
                raw = st.slider(f"{label} (Sustainalytics, lower=better)", 0.0, 50.0, 20.0, 0.5, key=key)
                return convert_to_100(raw, "sustainalytics")
            else:  # s&p
                raw = st.slider(f"{label} (S&P 0–100)", 0.0, 100.0, 55.0, 0.5, key=key)
                return convert_to_100(raw, "s&p")

        esg1_1, esg1_100 = esg_input_widget(a1, "a1", use_separate)
        st.markdown("---")
        esg2_1, esg2_100 = esg_input_widget(a2, "a2", use_separate)

    # ── Summary cards ────────────────────────────────────────────────────────
    st.markdown('<hr class="section-divider">', unsafe_allow_html=True)
    st.markdown('<p class="section-header">📌 Input Summary</p>', unsafe_allow_html=True)

    r1, r2 = r1_pct / 100, r2_pct / 100
    sd1, sd2 = sd1_pct / 100, sd2_pct / 100
    r_free = rf_pct / 100
    if gamma is None:
        gamma = 2  # fallback

    c1, c2, c3, c4, c5 = st.columns(5)
    for col, label, val, sub in [
        (c1, a1, f"{r1_pct:.1f}%", f"σ = {sd1_pct:.1f}%"),
        (c2, a2, f"{r2_pct:.1f}%", f"σ = {sd2_pct:.1f}%"),
        (c3, "Correlation", f"{rho:.2f}", "ρ"),
        (c4, "Risk-Free Rate", f"{rf_pct:.1f}%", "r_f"),
        (c5, "Lambda (λ)", f"{lambda_esg}", "ESG weight"),
    ]:
        col.markdown(f"""
        <div class="metric-card">
          <div class="metric-label">{label}</div>
          <div class="metric-value" style="font-size:1.4rem;">{val}</div>
          <div class="metric-sub">{sub}</div>
        </div>""", unsafe_allow_html=True)

    st.markdown(f"""
    <div class="success-box">
      ✅ All inputs received. Switch to the <strong>Results & Charts</strong> tab to see your optimised portfolios.
    </div>""", unsafe_allow_html=True)


# ═══════════════════════════════════════════════════════
# COMPUTE
# ═══════════════════════════════════════════════════════

if gamma is None:
    gamma = 2

r1, r2 = r1_pct / 100, r2_pct / 100
sd1, sd2 = sd1_pct / 100, sd2_pct / 100
r_free = rf_pct / 100

weights = np.linspace(0, 1, 1000)

returns, risks, esg_scores_100, sharpe_ratios, utilities_esg, utilities_no_esg = [], [], [], [], [], []

for w in weights:
    pr = portfolio_return(w, r1, r2)
    ps = portfolio_sd(w, sd1, sd2, rho)
    pe_100 = portfolio_esg(w, esg1_100, esg2_100)
    pe_1   = portfolio_esg(w, esg1_1, esg2_1)
    returns.append(pr)
    risks.append(ps)
    esg_scores_100.append(pe_100)
    sh = (pr - r_free) / ps if ps > 0 else -np.inf
    sharpe_ratios.append(sh)
    utilities_esg.append(pr - (gamma/2)*ps**2 + lambda_esg*pe_1)
    utilities_no_esg.append(pr - (gamma/2)*ps**2)

def best(idx_arr):
    i = np.argmax(idx_arr)
    return (weights[i], 1-weights[i], returns[i], risks[i], esg_scores_100[i])

i_tan = np.argmax(sharpe_ratios)
i_esg = np.argmax(utilities_esg)
i_noesg = np.argmax(utilities_no_esg)

w1_tan,     w2_tan,     r_tan,    sd_tan,    esg_tan    = best(sharpe_ratios)
w1_esg,     w2_esg,     r_esg,    sd_esg,    esg_esg    = best(utilities_esg)
w1_noesg,   w2_noesg,   r_noesg,  sd_noesg,  esg_noesg  = best(utilities_no_esg)

sharpe_tan   = (r_tan   - r_free) / sd_tan   if sd_tan   > 0 else 0
sharpe_esg   = (r_esg   - r_free) / sd_esg   if sd_esg   > 0 else 0
sharpe_noesg = (r_noesg - r_free) / sd_noesg if sd_noesg > 0 else 0

# ═══════════════════════════════════════════════════════
# TAB 2 – RESULTS
# ═══════════════════════════════════════════════════════
with tabs[1]:

    st.markdown('<p class="section-header">🏆 Optimal Portfolios</p>', unsafe_allow_html=True)

    def portfolio_card(title, icon, w1, w2, ret, risk, esg, sharpe, color):
        ec = esg_color(esg)
        bar1 = int(w1 * 100)
        bar2 = int(w2 * 100)
        st.markdown(f"""
        <div class="portfolio-card">
          <div class="portfolio-title" style="color:{color};">{icon} {title}</div>
          <div class="weight-bar-wrap">
            <div class="weight-bar-label"><span>{a1}</span><span>{w1*100:.1f}%</span></div>
            <div class="weight-bar-track"><div class="weight-bar-fill" style="width:{bar1}%;background:{color};"></div></div>
          </div>
          <div class="weight-bar-wrap">
            <div class="weight-bar-label"><span>{a2}</span><span>{w2*100:.1f}%</span></div>
            <div class="weight-bar-track"><div class="weight-bar-fill" style="width:{bar2}%;background:#4299e1;"></div></div>
          </div>
          <div style="display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:0.5rem;margin-top:1rem;">
            <div style="text-align:center;">
              <div style="font-size:0.7rem;color:#7a9bbf;text-transform:uppercase;letter-spacing:1px;">Return</div>
              <div style="font-size:1.2rem;font-weight:600;color:#e8f5f0;">{ret*100:.2f}%</div>
            </div>
            <div style="text-align:center;">
              <div style="font-size:0.7rem;color:#7a9bbf;text-transform:uppercase;letter-spacing:1px;">Risk (σ)</div>
              <div style="font-size:1.2rem;font-weight:600;color:#e8f5f0;">{risk*100:.2f}%</div>
            </div>
            <div style="text-align:center;">
              <div style="font-size:0.7rem;color:#7a9bbf;text-transform:uppercase;letter-spacing:1px;">Sharpe</div>
              <div style="font-size:1.2rem;font-weight:600;color:#e8f5f0;">{sharpe:.3f}</div>
            </div>
            <div style="text-align:center;">
              <div style="font-size:0.7rem;color:#7a9bbf;text-transform:uppercase;letter-spacing:1px;">ESG Score</div>
              <div style="font-size:1.2rem;font-weight:600;color:{ec};">{esg:.1f} <span style="font-size:0.7rem;">({esg_label(esg)})</span></div>
            </div>
          </div>
        </div>""", unsafe_allow_html=True)

    col_a, col_b, col_c = st.columns(3)
    with col_a:
        portfolio_card("Tangency Portfolio", "⭐", w1_tan, w2_tan, r_tan, sd_tan, esg_tan, sharpe_tan, "#f6c90e")
    with col_b:
        portfolio_card("Optimal (No ESG)", "💼", w1_noesg, w2_noesg, r_noesg, sd_noesg, esg_noesg, sharpe_noesg, "#a78bfa")
    with col_c:
        portfolio_card("Optimal (With ESG)", "🌱", w1_esg, w2_esg, r_esg, sd_esg, esg_esg, sharpe_esg, "#52e89b")

    # ── Charts ───────────────────────────────────────────────────────────────
    st.markdown('<hr class="section-divider">', unsafe_allow_html=True)
    st.markdown('<p class="section-header">📈 Charts</p>', unsafe_allow_html=True)

    apply_dark_style()

    chart_col1, chart_col2 = st.columns(2)

    # Chart 1 – Efficient Frontier
    with chart_col1:
        st.markdown("**Efficient Frontier with ESG Colouring**")
        fig1, ax1 = plt.subplots(figsize=(7, 5))

        scatter = ax1.scatter(risks, returns, c=esg_scores_100, cmap="YlGn", s=20, alpha=0.85, zorder=2)
        plt.colorbar(scatter, ax=ax1, label="Portfolio ESG Score (0–100)")

        ax1.plot(risks, returns, color="#4299e1", linewidth=1.5, alpha=0.5, zorder=1)

        if sd_tan > 0:
            sd_max = max(risks) * 1.3
            sd_cml = np.linspace(0, sd_max, 100)
            ret_cml = r_free + ((r_tan - r_free) / sd_tan) * sd_cml
            ax1.plot(sd_cml, ret_cml, "--", color="#52e89b", linewidth=1.8, alpha=0.8, label="Capital Market Line")

        ax1.scatter(r_free*0, r_free, color="#52e89b", s=90, marker="s", label="Risk-Free", zorder=5)
        ax1.scatter(sd_tan, r_tan, color="#f6c90e", s=160, marker="*", label="Tangency", zorder=5)
        ax1.scatter(sd_noesg, r_noesg, color="#a78bfa", s=100, marker="X", label="Optimal (No ESG)", zorder=5)
        ax1.scatter(sd_esg, r_esg, color="#52e89b", s=100, marker="D", label="Optimal (With ESG)", zorder=5)

        ax1.set_xlabel("Risk (Standard Deviation)")
        ax1.set_ylabel("Expected Return")
        ax1.set_title("Portfolio Frontier", color="#e8edf5", fontsize=13)
        ax1.legend(fontsize=8)
        ax1.grid(True)
        fig1.tight_layout()
        st.pyplot(fig1)
        plt.close(fig1)

    # Chart 2 – ESG–Sharpe Frontier
    with chart_col2:
        st.markdown("**ESG–Sharpe Ratio Frontier**")
        fig2, ax2 = plt.subplots(figsize=(7, 5))

        esg_vals = [portfolio_esg(w, esg1_100, esg2_100) for w in weights]
        ax2.plot(esg_vals, sharpe_ratios, color="#52e89b", linewidth=2, label="ESG–Sharpe Frontier")

        ax2.scatter(esg_tan,   sharpe_tan,   color="#f6c90e", s=160, marker="*", label="Tangency", zorder=5)
        ax2.scatter(esg_noesg, sharpe_noesg, color="#a78bfa", s=100, marker="X", label="Optimal (No ESG)", zorder=5)
        ax2.scatter(esg_esg,   sharpe_esg,   color="#38b2ac", s=100, marker="D", label="Optimal (With ESG)", zorder=5)

        ax2.set_xlabel("Portfolio ESG Score (0–100)")
        ax2.set_ylabel("Sharpe Ratio")
        ax2.set_title("ESG–Sharpe Frontier", color="#e8edf5", fontsize=13)
        ax2.legend(fontsize=8)
        ax2.grid(True)
        fig2.tight_layout()
        st.pyplot(fig2)
        plt.close(fig2)

    # Chart 3 – Weight vs ESG / Return / Risk
    st.markdown("**Portfolio Composition Across All Weights**")
    fig3, axes = plt.subplots(1, 3, figsize=(14, 4))

    for ax, y_data, ylabel, color, title in [
        (axes[0], [portfolio_esg(w, esg1_100, esg2_100) for w in weights], "ESG Score (0–100)", "#52e89b", "ESG Score"),
        (axes[1], [r*100 for r in returns], "Expected Return (%)", "#4299e1", "Return"),
        (axes[2], [r*100 for r in risks], "Risk / σ (%)", "#f87171", "Risk"),
    ]:
        ax.plot(weights*100, y_data, color=color, linewidth=2)
        ax.axvline(w1_esg*100, color="#52e89b", linestyle="--", alpha=0.7, linewidth=1.2, label=f"ESG Optimal")
        ax.axvline(w1_tan*100, color="#f6c90e", linestyle=":",  alpha=0.7, linewidth=1.2, label=f"Tangency")
        ax.set_xlabel(f"{a1} weight (%)")
        ax.set_ylabel(ylabel)
        ax.set_title(title, color="#e8edf5")
        ax.legend(fontsize=7)
        ax.grid(True)

    fig3.tight_layout()
    st.pyplot(fig3)
    plt.close(fig3)

    # ── Comparison table ──────────────────────────────────────────────────────
    st.markdown('<hr class="section-divider">', unsafe_allow_html=True)
    st.markdown('<p class="section-header">📋 Comparison Table</p>', unsafe_allow_html=True)

    import pandas as pd
    df = pd.DataFrame({
        "Portfolio":        ["Tangency", "Optimal (No ESG)", "Optimal (With ESG)"],
        f"{a1} weight":     [f"{w1_tan*100:.1f}%",   f"{w1_noesg*100:.1f}%",   f"{w1_esg*100:.1f}%"],
        f"{a2} weight":     [f"{w2_tan*100:.1f}%",   f"{w2_noesg*100:.1f}%",   f"{w2_esg*100:.1f}%"],
        "Exp. Return":      [f"{r_tan*100:.2f}%",   f"{r_noesg*100:.2f}%",   f"{r_esg*100:.2f}%"],
        "Risk (σ)":         [f"{sd_tan*100:.2f}%",  f"{sd_noesg*100:.2f}%",  f"{sd_esg*100:.2f}%"],
        "Sharpe Ratio":     [f"{sharpe_tan:.4f}",   f"{sharpe_noesg:.4f}",   f"{sharpe_esg:.4f}"],
        "ESG Score (0–100)":[f"{esg_tan:.2f}",      f"{esg_noesg:.2f}",      f"{esg_esg:.2f}"],
    })
    st.dataframe(df.set_index("Portfolio"), use_container_width=True)

    st.markdown("""
    <div class="info-box" style="margin-top:1rem;">
      <strong>Note:</strong> ESG scores are displayed on a 0–100 scale.
      The utility function uses a 0–1 normalised ESG scale internally.
      γ (gamma) controls risk aversion; λ (lambda) controls ESG preference strength.
    </div>""", unsafe_allow_html=True)