# -*- coding: utf-8 -*-
"""Sustainable claude main - gpt adjusted

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bF9tsYmoH-l9XN4Mf7JT9-fc8UFm_AVo
"""

import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter

# ──────────────────────────────────────────────────────────
# PAGE CONFIG
# ──────────────────────────────────────────────────────────
st.set_page_config(
    page_title="EcoVest · Sustainable Portfolio",
    page_icon="🌿",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ──────────────────────────────────────────────────────────
# GLOBAL CSS
# ──────────────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&family=Playfair+Display:wght@500;600&display=swap');

/* ───────────────── GLOBAL ───────────────── */
html, body, [class*="css"] {
    font-family: 'Inter', sans-serif;
    background-color: #f4f7f5;
    color: #1c2b22;
}

/* ───────────────── SIDEBAR ───────────────── */
[data-testid="stSidebar"] {
    background: #0f2a1d;
    border-right: 1px solid #1f3d2b;
}
[data-testid="stSidebar"] * {
    color: #dbece0 !important;
}
[data-testid="stSidebar"] .stMarkdown h3 {
    color: #6fcf97 !important;
    font-size: 12px !important;
    letter-spacing: 0.12em;
    text-transform: uppercase;
}
[data-testid="stSidebar"] input,
[data-testid="stSidebar"] .stSelectbox > div > div {
    background: #163825 !important;
    border: 1px solid #2d5a3f !important;
    border-radius: 8px !important;
}

/* ───────────────── HEADER ───────────────── */
.page-header h1 {
    font-family: 'Playfair Display', serif;
    font-size: 42px;
    color: #10281c;
}
.page-header p {
    color: #5f7d6c;
}

/* ───────────────── SECTION LABEL ───────────────── */
.section-label {
    font-size: 11px;
    font-weight: 600;
    letter-spacing: 0.14em;
    color: #3f8f63;
    margin-top: 30px;
}

/* ───────────────── CARD ───────────────── */
.card {
    background: #ffffff;
    border: 1px solid #e2ece6;
    border-radius: 16px;
    padding: 22px;
    box-shadow: 0 6px 18px rgba(16, 40, 28, 0.04);
}

/* ───────────────── METRIC ───────────────── */
.metric-tile {
    background: #ffffff;
    border: 1px solid #e6efe9;
    border-radius: 14px;
    padding: 16px;
}
.metric-tile .label {
    font-size: 11px;
    color: #6b8f7b;
}
.metric-tile .value {
    font-size: 28px;
    font-weight: 600;
}

/* ───────────────── BARS ───────────────── */
.bar-track {
    height: 18px;
    background: #edf4ef;
}
.bar-fill {
    border-radius: 100px;
}

/* ───────────────── TABLE ───────────────── */
.cmp-table th {
    background: #10281c;
    color: #b7d7c4;
}
.cmp-table td {
    font-size: 13px;
}

/* ───────────────── CHIPS ───────────────── */
.chip-pos {
    background: #e6f7ec;
    color: #1f7a4c;
}
.chip-neg {
    background: #fdeaea;
    color: #b42318;
}
.chip-neu {
    background: #eef2f1;
    color: #5f6f68;
}

/* ───────────────── DIVIDER ───────────────── */
.fancy-divider {
    background: linear-gradient(90deg, #2f7d57, #7cc9a6, transparent);
}

/* ───────────────── INFO BOX ───────────────── */
.info-box {
    background: #edf7f1;
    border-left: 4px solid #3f8f63;
}
.warn-box {
    background: #fff6e5;
    border-left: 4px solid #e6a700;
}

/* ───────────────── BUTTON ───────────────── */
[data-testid="stSidebar"] .stButton > button {
    background: linear-gradient(135deg, #2f7d57, #4caf7a) !important;
    border-radius: 10px !important;
    font-weight: 600 !important;
}

/* ───────────────── FOOTER ───────────────── */
.footer {
    color: #8aa79a;
    font-size: 12px;
}
</style>
""", unsafe_allow_html=True)


# ──────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ──────────────────────────────────────────────────────────

def esg_hex(score: float) -> str:
    """Gradient colour: red(0) → amber(50) → green(100)."""
    score = max(0.0, min(100.0, score))
    if score <= 50:
        t = score / 50.0
        r = 239; g = int(68  + t * (180 - 68));  b = int(68 + t * (8 - 68))
    else:
        t = (score - 50.0) / 50.0
        r = int(234 + t * (34  - 234))
        g = int(180 + t * (197 - 180))
        b = int(8   + t * (94  - 8))
    return f"#{r:02x}{g:02x}{b:02x}"


def progress_ring_html(score: float, subtitle: str = "ESG Score") -> str:
    col   = esg_hex(score)
    R     = 52
    circ  = 2 * np.pi * R
    dash  = (score / 100) * circ
    gap   = circ - dash
    bg    = esg_hex(score) + "22"  # semi-transparent ring bg
    return f"""
    <div style="display:flex;flex-direction:column;align-items:center;gap:6px;">
      <svg width="148" height="148" viewBox="0 0 120 120">
        <circle cx="60" cy="60" r="{R}" fill="none"
                stroke="{col}22" stroke-width="13"/>
        <circle cx="60" cy="60" r="{R}" fill="none"
                stroke="{col}" stroke-width="13"
                stroke-dasharray="{dash:.2f} {gap:.2f}"
                stroke-linecap="round"
                transform="rotate(-90 60 60)"/>
        <text x="60" y="55" text-anchor="middle"
              font-family="DM Sans, sans-serif"
              font-size="22" font-weight="700" fill="{col}">{score:.1f}</text>
        <text x="60" y="71" text-anchor="middle"
              font-family="DM Sans, sans-serif"
              font-size="11" fill="#94a3b8">/ 100</text>
      </svg>
      <span style="font-size:12px;font-weight:600;letter-spacing:0.08em;
                   text-transform:uppercase;color:#6b7b6e;">{subtitle}</span>
    </div>"""


def alloc_bar_html(w1: float, w2: float, name1: str, name2: str) -> str:
    c1, c2 = "#2e7d36", "#3b82f6"
    pct1 = f"{w1*100:.1f}%"
    pct2 = f"{w2*100:.1f}%"
    return f"""
    <div class="bar-row">
      <div class="bar-label-row">
        <span style="color:{c1};">{name1}</span>
        <span style="color:{c1};">{pct1}</span>
      </div>
      <div class="bar-track">
        <div class="bar-fill" style="width:{pct1};background:{c1};"></div>
      </div>
    </div>
    <div class="bar-row" style="margin-top:12px;">
      <div class="bar-label-row">
        <span style="color:{c2};">{name2}</span>
        <span style="color:{c2};">{pct2}</span>
      </div>
      <div class="bar-track">
        <div class="bar-fill" style="width:{pct2};background:{c2};"></div>
      </div>
    </div>"""


def metric_tile(label: str, value: str, sub: str = "") -> str:
    sub_html = f'<div class="sub">{sub}</div>' if sub else ""
    return f"""
    <div class="metric-tile">
      <div class="label">{label}</div>
      <div class="value">{value}</div>
      {sub_html}
    </div>"""


def chip_html(value: float, suffix: str = "", decimals: int = 2) -> str:
    fmt = f"{value:+.{decimals}f}{suffix}"
    if value > 0.001:
        cls = "chip-pos"
    elif value < -0.001:
        cls = "chip-neg"
    else:
        cls = "chip-neu"
    return f'<span class="chip {cls}">{fmt}</span>'


def convert_to_100(score, agency: str) -> float:
    agency = agency.lower()
    if agency == "sustainalytics":
        v = float(score)
        return max(0.0, min(100.0, 100 - (v / 50) * 100)) if v < 50 else 0.0
    elif agency == "msci":
        msci_map = {
            "ccc": 0.0, "b": 16.7, "bb": 33.4, "bbb": 50.1,
            "a": 66.8, "aa": 83.5, "aaa": 100.0,
        }
        return msci_map.get(str(score).strip().lower(), 50.0)
    elif agency == "refinitiv":
        refinitiv_map = {0: 0, 1: 10, 2: 25, 3: 50, 4: 75, 5: 95}
        return float(refinitiv_map.get(int(float(score)), 50))
    else:  # s&p
        return max(0.0, min(100.0, float(score)))


def p_return(w1, r1, r2):   return w1 * r1 + (1 - w1) * r2
def p_sd(w1, sd1, sd2, rho):
    return np.sqrt(w1**2*sd1**2 + (1-w1)**2*sd2**2 + 2*rho*w1*(1-w1)*sd1*sd2)
def p_esg(w1, e1, e2):      return w1 * e1 + (1 - w1) * e2


# ──────────────────────────────────────────────────────────
# SIDEBAR  ─  ALL INPUTS
# ──────────────────────────────────────────────────────────
sb = st.sidebar

sb.markdown("""
<div style="padding:18px 0 10px;text-align:center;">
  <span style="font-family:'DM Serif Display',serif;font-size:26px;
               color:#7ec984;letter-spacing:0.02em;">🌿 EcoVest</span><br>
  <span style="font-size:11px;color:#4a6b4e;letter-spacing:0.1em;
               text-transform:uppercase;">Sustainable Portfolio Tool</span>
</div>
""", unsafe_allow_html=True)

sb.markdown("---")

# ── SECTION 1 · ASSETS ────────────────────────────────────
sb.markdown("### Assets")

name1 = sb.text_input("Asset 1 name", "Apple (AAPL)", key="name1")
name2 = sb.text_input("Asset 2 name", "Microsoft (MSFT)", key="name2")

sb.markdown(f"**{name1}**")
r1_pct  = sb.number_input("Expected return (%)", value=10.0, step=0.5, key="r1")
sd1_pct = sb.number_input("Volatility / Std Dev (%)", value=18.0, min_value=0.01, step=0.5, key="sd1")

sb.markdown(f"**{name2}**")
r2_pct  = sb.number_input("Expected return (%) ", value=8.0, step=0.5, key="r2")
sd2_pct = sb.number_input("Volatility / Std Dev (%) ", value=14.0, min_value=0.01, step=0.5, key="sd2")

sb.markdown("**Market parameters**")
rho    = sb.slider("Correlation", -1.0, 1.0, 0.40, 0.01)
rfr    = sb.number_input("Risk-free rate (%)", value=4.5, step=0.1)

r1 = r1_pct / 100;  r2 = r2_pct / 100
sd1 = sd1_pct / 100; sd2 = sd2_pct / 100
r_free = rfr / 100

sb.markdown("---")

# ── SECTION 2 · RISK PREFERENCE ───────────────────────────
sb.markdown("### Risk Preference")

know_gamma = sb.radio(
    "Do you know your risk aversion (gamma)?",
    ["Yes — enter it directly", "No — take the questionnaire"],
    key="know_gamma",
)

if know_gamma == "Yes — enter it directly":
    gamma = sb.slider(
        "Gamma  (−10 = risk-loving · 0 = neutral · +10 = risk-averse)",
        -10.0, 10.0, 3.0, 0.5, key="gamma_direct",
    )
else:
    sb.caption("Answer all 5 questions as honestly as you can.")

    q1 = sb.radio(
        "Q1. What best describes your attitude to investment risk?",
        ["1 — I avoid risk wherever possible",
         "2 — I prefer low-risk, steady options",
         "3 — I am comfortable with moderate risk",
         "4 — I am willing to take on risk for higher returns",
         "5 — I actively seek high-risk, high-reward opportunities"],
        key="q1",
    )
    q2 = sb.radio(
        'Q2. "I prefer slow, steady growth even if returns are lower."',
        ["1 — Strongly agree", "2 — Tend to agree", "3 — In between",
         "4 — Tend to disagree", "5 — Strongly disagree"],
        key="q2",
    )
    q3 = sb.radio(
        "Q3. Your portfolio falls 20% in three months. You:",
        ["1 — Sell everything to stop the bleeding",
         "2 — Sell some to reduce exposure",
         "3 — Do nothing and wait for recovery",
         "4 — Review but stay the course",
         "5 — Buy more — it is a great opportunity"],
        key="q3",
    )
    q4 = sb.radio(
        "Q4. What proportion would you put in a high-risk, high-reward investment?",
        ["1 — Very little, if any", "2 — Less than a quarter",
         "3 — Around half", "4 — More than half", "5 — All of it"],
        key="q4",
    )
    q5 = sb.radio(
        'Q5. "I always prefer a small guaranteed return over a larger uncertain one."',
        ["1 — Strongly agree", "2 — Tend to agree", "3 — In between",
         "4 — Tend to disagree", "5 — Strongly disagree"],
        key="q5",
    )

    scores = [int(q[0]) for q in [q1, q2, q3, q4, q5]]
    avg = sum(scores) / 5

    if   avg <= 1.5: gamma, glabel = 8,  "Very Cautious"
    elif avg <= 2.3: gamma, glabel = 4,  "Cautious"
    elif avg <= 3.2: gamma, glabel = 0,  "Moderate / Risk-Neutral"
    elif avg <= 4.1: gamma, glabel = -4, "Adventurous"
    else:            gamma, glabel = -8, "Very Adventurous"

    sb.success(f"Profile: **{glabel}** · γ = {gamma}")

sb.markdown("---")

# ── SECTION 3 · ESG PREFERENCES ───────────────────────────
sb.markdown("### ESG Preferences")

lambda_choice = sb.radio(
    "How important are ESG factors to you?",
    ["1 — Not at all (financial returns only)",
     "2 — Slightly important",
     "3 — Moderately important",
     "4 — Very important — a key priority"],
    key="lambda_choice",
)
lambda_map = {"1": 0.0, "2": 0.25, "3": 0.75, "4": 1.0}
lambda_esg = lambda_map[lambda_choice[0]]

sb.markdown("---")

# ── SECTION 4 · ESG SCORES ────────────────────────────────
sb.markdown("### ESG Scores")

esg_method = sb.radio(
    "How would you like to enter ESG scores?",
    ["Overall ESG score per asset", "Separate E, S, G scores per asset"],
    key="esg_method",
)
use_separate = esg_method == "Separate E, S, G scores per asset"

weights_ok = True
wE = wS = wG = 33.333

if use_separate:
    sb.markdown("**Pillar weights (must sum to 100%)**")
    wE = sb.number_input("Environmental (%)", 0.0, 100.0, 40.0, key="wE")
    wS = sb.number_input("Social (%)",        0.0, 100.0, 30.0, key="wS")
    wG = sb.number_input("Governance (%)",    0.0, 100.0, 30.0, key="wG")
    weights_ok = abs(wE + wS + wG - 100) < 0.5
    if not weights_ok:
        sb.warning(f"Weights sum to {wE+wS+wG:.1f}% — must equal 100%.")

AGENCIES       = ["Sustainalytics (0–50, lower=better)",
                  "Refinitiv / LSEG (0–5)",
                  "MSCI (CCC → AAA)",
                  "S&P Global (0–100)"]
AGENCY_KEYS    = ["sustainalytics", "refinitiv", "msci", "s&p"]
MSCI_GRADES    = ["AAA", "AA", "A", "BBB", "BB", "B", "CCC"]


def esg_block(label: str, prefix: str) -> float:
    """Render ESG score inputs for one asset; return normalised 0-100 score."""
    sb.markdown(f"**{label}**")
    ag_sel = sb.selectbox("Rating agency", AGENCIES, key=f"{prefix}_ag")
    ag     = AGENCY_KEYS[AGENCIES.index(ag_sel)]

    def one_pillar(pillar_label: str, pkey: str) -> float:
        if ag == "msci":
            raw = sb.selectbox(pillar_label, MSCI_GRADES, key=pkey)
        elif ag == "refinitiv":
            raw = sb.select_slider(pillar_label, [0, 1, 2, 3, 4, 5], value=3, key=pkey)
        elif ag == "sustainalytics":
            raw = sb.number_input(pillar_label + " (0–50+)", 0.0, 60.0, 15.0, key=pkey)
        else:
            raw = sb.number_input(pillar_label + " (0–100)", 0.0, 100.0, 70.0, key=pkey)
        return convert_to_100(raw, ag)

    if use_separate:
        e100 = one_pillar("E score", f"{prefix}_e")
        s100 = one_pillar("S score", f"{prefix}_s")
        g100 = one_pillar("G score", f"{prefix}_g")
        overall = (wE / 100) * e100 + (wS / 100) * s100 + (wG / 100) * g100
    else:
        overall = one_pillar("Overall ESG score", f"{prefix}_ov")

    sb.caption(f"Normalised score: **{overall:.1f} / 100**")
    return overall


esg1_100 = esg_block(name1, "a1")
esg2_100 = esg_block(name2, "a2")
esg1_1   = esg1_100 / 100
esg2_1   = esg2_100 / 100

sb.markdown("---")
run = sb.button("Calculate Portfolio ›", key="run")


# ──────────────────────────────────────────────────────────
# MAIN PAGE HEADER
# ──────────────────────────────────────────────────────────
st.markdown("""
<div class="page-header">
  <h1>Sustainable Finance<br>Portfolio Tool</h1>
  <p>Personalised portfolios balancing financial returns and ESG impact.</p>
</div>
""", unsafe_allow_html=True)

if not run:
    st.markdown("""
    <div class="info-box">
      👈  Fill in your preferences in the sidebar, then click
      <strong>Calculate Portfolio</strong> to see your results.
    </div>
    """, unsafe_allow_html=True)
    st.stop()

if not weights_ok:
    st.markdown("""
    <div class="warn-box">
      ⚠️ ESG pillar weights must sum to 100%. Please adjust them in the sidebar.
    </div>
    """, unsafe_allow_html=True)
    st.stop()


# ──────────────────────────────────────────────────────────
# PORTFOLIO CALCULATIONS
# ──────────────────────────────────────────────────────────
W = np.linspace(0, 1, 1000)

rets, sds, esgs_100, sharpes = [], [], [], []
util_esg, util_no_esg = [], []

for w in W:
    pr  = p_return(w, r1, r2)
    ps  = p_sd(w, sd1, sd2, rho)
    pe  = p_esg(w, esg1_100, esg2_100)
    pe1 = p_esg(w, esg1_1,   esg2_1)
    rets.append(pr); sds.append(ps); esgs_100.append(pe)
    sh = (pr - r_free) / ps if ps > 0 else -np.inf
    sharpes.append(sh)
    util_esg.append(pr     - (gamma / 2) * ps**2 + lambda_esg * pe1)
    util_no_esg.append(pr  - (gamma / 2) * ps**2)

# ── Unconstrained tangency ─────────────────────────────
idx_t    = int(np.argmax(sharpes))
w1_t     = W[idx_t]
ret_t    = rets[idx_t];  sd_t    = sds[idx_t]
esg_t    = esgs_100[idx_t]; sharpe_t = sharpes[idx_t]

# ── ESG threshold & constrained frontier ──────────────
esg_lo, esg_hi = min(esg1_100, esg2_100), max(esg1_100, esg2_100)
esg_threshold  = esg_lo + lambda_esg * (esg_hi - esg_lo)

elig_w, elig_r, elig_s, elig_e, elig_sh = [], [], [], [], []
for i, w in enumerate(W):
    if esgs_100[i] >= esg_threshold:
        elig_w.append(w);        elig_r.append(rets[i])
        elig_s.append(sds[i]);   elig_e.append(esgs_100[i])
        sh = (rets[i] - r_free) / sds[i] if sds[i] > 0 else -np.inf
        elig_sh.append(sh)

if len(elig_w) == 0:
    st.error("No portfolios satisfy your ESG threshold. "
             "Try reducing your ESG preference (lambda).")
    st.stop()

idx_te   = int(np.argmax(elig_sh))
w1_te    = elig_w[idx_te]
ret_te   = elig_r[idx_te];  sd_te   = elig_s[idx_te]
esg_te   = elig_e[idx_te];  sharpe_te = elig_sh[idx_te]

# ── Capital allocation (no leverage, capped 0-1) ──────
def cap_alloc(ret_p, sd_p):
    if gamma > 0 and sd_p > 0:
        return float(np.clip((ret_p - r_free) / (gamma * sd_p**2), 0, 1))
    return 1.0

y_all = cap_alloc(ret_t,  sd_t)
y_esg = cap_alloc(ret_te, sd_te)


# ──────────────────────────────────────────────────────────
# SECTION A · ESG OPTIMAL PORTFOLIO
# ──────────────────────────────────────────────────────────
st.markdown('<div class="section-label">ESG Optimal Portfolio</div>',
            unsafe_allow_html=True)

col_alloc, col_ring, col_metrics = st.columns([2.4, 1.2, 2.4])

with col_alloc:
    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.markdown("**Asset Allocation (Risky Portfolio)**")
    st.markdown(
        alloc_bar_html(w1_te, 1 - w1_te, name1, name2),
        unsafe_allow_html=True,
    )
    st.markdown("<br>", unsafe_allow_html=True)
    # Risk-free split
    rf_pct = (1 - y_esg) * 100
    rp_pct = y_esg * 100
    st.caption(
        f"Overall allocation — Risky portfolio: **{rp_pct:.1f}%** · "
        f"Risk-free asset: **{rf_pct:.1f}%**"
    )
    st.markdown('</div>', unsafe_allow_html=True)

with col_ring:
    st.markdown(
        progress_ring_html(esg_te, "Portfolio ESG"),
        unsafe_allow_html=True,
    )

with col_metrics:
    st.markdown(
        metric_tile("Expected Return",  f"{ret_te*100:.2f}%", "Annualised"),
        unsafe_allow_html=True,
    )
    st.markdown(
        metric_tile("Risk (Std Dev)",   f"{sd_te*100:.2f}%",  "Annualised"),
        unsafe_allow_html=True,
    )
    st.markdown(
        metric_tile("Sharpe Ratio",     f"{sharpe_te:.4f}",   "Risk-adjusted return"),
        unsafe_allow_html=True,
    )

st.markdown('<hr class="fancy-divider">', unsafe_allow_html=True)

# ──────────────────────────────────────────────────────────
# SECTION B · PORTFOLIO COMPARISON TABLE
# ──────────────────────────────────────────────────────────
st.markdown('<div class="section-label">Portfolio Comparison</div>',
            unsafe_allow_html=True)

rows = [
    ("Metric",                  "ESG-Constrained",            "Unconstrained"),
    (f"{name1} weight",         f"{w1_te*100:.1f}%",          f"{w1_t*100:.1f}%"),
    (f"{name2} weight",         f"{(1-w1_te)*100:.1f}%",      f"{(1-w1_t)*100:.1f}%"),
    ("Expected return",         f"{ret_te*100:.2f}%",         f"{ret_t*100:.2f}%"),
    ("Risk (Std Dev)",          f"{sd_te*100:.2f}%",          f"{sd_t*100:.2f}%"),
    ("ESG score (0–100)",       f"{esg_te:.1f}",              f"{esg_t:.1f}"),
    ("Sharpe ratio",            f"{sharpe_te:.4f}",           f"{sharpe_t:.4f}"),
    ("Weight in risky portf.",  f"{y_esg*100:.1f}%",          f"{y_all*100:.1f}%"),
    ("Weight in risk-free",     f"{(1-y_esg)*100:.1f}%",      f"{(1-y_all)*100:.1f}%"),
]

table_html = '<table class="cmp-table"><thead><tr>'
for h in rows[0]:
    table_html += f"<th>{h}</th>"
table_html += "</tr></thead><tbody>"
for row in rows[1:]:
    table_html += "<tr>"
    table_html += f'<td>{row[0]}</td>'
    table_html += f'<td class="esg-col">{row[1]}</td>'
    table_html += f'<td class="trad-col">{row[2]}</td>'
    table_html += "</tr>"
table_html += "</tbody></table>"

st.markdown(table_html, unsafe_allow_html=True)

st.markdown('<hr class="fancy-divider">', unsafe_allow_html=True)

# ──────────────────────────────────────────────────────────
# SECTION C · IMPACT OF ESG CONSTRAINT
# ──────────────────────────────────────────────────────────
st.markdown('<div class="section-label">Impact of ESG Constraint</div>',
            unsafe_allow_html=True)

d_ret = ret_te - ret_t
d_sd  = sd_te  - sd_t
d_esg = esg_te - esg_t

ic1, ic2, ic3 = st.columns(3)

with ic1:
    st.markdown(f"""
    <div class="card" style="text-align:center;">
      <div class="label" style="text-align:center;margin-bottom:8px;">Return change</div>
      {chip_html(d_ret * 100, " pp")}
      <div style="font-size:11px;color:#9ca3af;margin-top:6px;">vs unconstrained</div>
    </div>""", unsafe_allow_html=True)

with ic2:
    st.markdown(f"""
    <div class="card" style="text-align:center;">
      <div class="label" style="text-align:center;margin-bottom:8px;">Risk change</div>
      {chip_html(d_sd * 100, " pp")}
      <div style="font-size:11px;color:#9ca3af;margin-top:6px;">vs unconstrained</div>
    </div>""", unsafe_allow_html=True)

with ic3:
    st.markdown(f"""
    <div class="card" style="text-align:center;">
      <div class="label" style="text-align:center;margin-bottom:8px;">ESG score gain</div>
      {chip_html(d_esg, " pts", decimals=1)}
      <div style="font-size:11px;color:#9ca3af;margin-top:6px;">vs unconstrained</div>
    </div>""", unsafe_allow_html=True)

st.markdown("<br>", unsafe_allow_html=True)

if esg_t >= esg_threshold:
    st.markdown("""
    <div class="info-box">
      The unconstrained optimal portfolio already meets your ESG threshold —
      applying the constraint has no material effect on the allocation.
    </div>""", unsafe_allow_html=True)
else:
    st.markdown("""
    <div class="info-box">
      Your ESG preference excludes some portfolio combinations, shifting the
      optimal allocation towards higher-rated assets. The chips above show the
      cost (return / risk) and benefit (ESG score) of that tilt.
    </div>""", unsafe_allow_html=True)

st.markdown('<hr class="fancy-divider">', unsafe_allow_html=True)

# ──────────────────────────────────────────────────────────
# SECTION D · INPUT SUMMARY (collapsible)
# ──────────────────────────────────────────────────────────
with st.expander("📋  Input Summary"):
    left, right = st.columns(2)
    with left:
        st.markdown("**Your parameters**")
        st.dataframe(
            pd.DataFrame({
                "Parameter":  ["Risk aversion (γ)", "ESG preference (λ)",
                                "ESG threshold", "Risk-free rate"],
                "Value":      [f"{gamma:.2f}", f"{lambda_esg:.2f}",
                                f"{esg_threshold:.1f} / 100", f"{r_free*100:.2f}%"],
            }),
            use_container_width=True, hide_index=True,
        )
    with right:
        st.markdown("**Individual asset ESG scores**")
        st.dataframe(
            pd.DataFrame({
                "Asset":      [name1, name2],
                "ESG (0-100)":[f"{esg1_100:.1f}", f"{esg2_100:.1f}"],
            }),
            use_container_width=True, hide_index=True,
        )

st.markdown('<hr class="fancy-divider">', unsafe_allow_html=True)

# ──────────────────────────────────────────────────────────
# SECTION E · CHARTS
# ──────────────────────────────────────────────────────────
st.markdown('<div class="section-label">Charts</div>', unsafe_allow_html=True)

# Frontier data (extended range for display)
W_plot = np.linspace(-1.0, 2.0, 1200)
ret_fp = [p_return(w, r1, r2)     for w in W_plot]
sd_fp  = [p_sd(w, sd1, sd2, rho)  for w in W_plot]
esg_fp = [p_esg(w, esg1_100, esg2_100) for w in W_plot]

sd_fp_esg  = [sd_fp[i]  for i in range(len(W_plot)) if esg_fp[i] >= esg_threshold]
ret_fp_esg = [ret_fp[i] for i in range(len(W_plot)) if esg_fp[i] >= esg_threshold]

sd_max   = max(max(sd_fp), sd_t, sd_te) * 1.08
sd_range = np.linspace(0, sd_max, 300)
cml_all  = r_free + ((ret_t  - r_free) / sd_t)  * sd_range if sd_t  > 0 else np.zeros(300)
cml_esg  = r_free + ((ret_te - r_free) / sd_te) * sd_range if sd_te > 0 else np.zeros(300)

# ESG–Sharpe data (0–1 weights only)
W_es   = np.linspace(0, 1, 400)
esg_es = [p_esg(w, esg1_100, esg2_100) for w in W_es]
sh_es  = []
for w in W_es:
    ps = p_sd(w, sd1, sd2, rho)
    pr = p_return(w, r1, r2)
    sh_es.append((pr - r_free) / ps if ps > 0 else np.nan)

# Shared style
plt.rcParams.update({
    "font.family":     "sans-serif",
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.grid":       True,
    "grid.alpha":      0.25,
    "grid.linestyle":  "--",
})

chart_col1, chart_col2 = st.columns(2)

# ── Chart 1 · Efficient Frontier ────────────────────────
with chart_col1:
    fig1, ax1 = plt.subplots(figsize=(6, 5))
    fig1.patch.set_facecolor("#f7faf7")
    ax1.set_facecolor("#f7faf7")

    ax1.plot(sd_fp,     ret_fp,     color="#94a3b8", lw=2,   label="All portfolios")
    ax1.plot(sd_fp_esg, ret_fp_esg, color="#22c55e", lw=2.5, label="ESG-eligible")
    ax1.plot(sd_range,  cml_all,    "--", color="#94a3b8", lw=1.5, label="CML (unconstrained)")
    ax1.plot(sd_range,  cml_esg,    "--", color="#16a34a", lw=1.5, label="CML (ESG)")

    ax1.scatter(0,      r_free,  marker="s", s=80,  color="#0d1f0f",
                zorder=5, label="Risk-free asset")
    ax1.scatter(sd_t,   ret_t,   marker="*", s=220, color="#64748b",
                edgecolors="white", linewidths=0.8, zorder=6,
                label="Optimal (unconstrained)")
    ax1.scatter(sd_te,  ret_te,  marker="*", s=220, color="#16a34a",
                edgecolors="white", linewidths=0.8, zorder=7,
                label="Optimal (ESG)")

    ax1.annotate("Unconstrained", (sd_t, ret_t),
                 xytext=(-6, -16), textcoords="offset points",
                 fontsize=8, color="#64748b")
    ax1.annotate("ESG optimal",   (sd_te, ret_te),
                 xytext=(8, 6),   textcoords="offset points",
                 fontsize=8, color="#16a34a")

    x_vals = sd_fp + [0]
    y_vals = ret_fp + [r_free]
    ax1.set_xlim(0, max(x_vals) * 1.02)
    ax1.set_ylim(min(y_vals) - 0.01, max(y_vals) + 0.01)
    ax1.xaxis.set_major_formatter(PercentFormatter(1.0))
    ax1.yaxis.set_major_formatter(PercentFormatter(1.0))
    ax1.set_xlabel("Risk (Standard Deviation)", fontsize=11)
    ax1.set_ylabel("Expected Return",           fontsize=11)
    ax1.set_title("Efficient Frontier",         fontsize=13, fontweight="bold",
                  color="#0d1f0f")
    ax1.legend(fontsize=7.5)
    plt.tight_layout()
    st.pyplot(fig1)
    st.caption(
        "Blue/grey line: full frontier. Green line: portfolios meeting your ESG threshold. "
        "Stars mark the tangency (highest Sharpe) portfolio in each case."
    )

# ── Chart 2 · ESG–Sharpe Frontier ───────────────────────
with chart_col2:
    fig2, ax2 = plt.subplots(figsize=(6, 5))
    fig2.patch.set_facecolor("#f7faf7")
    ax2.set_facecolor("#f7faf7")

    ax2.plot(esg_es, sh_es, color="#ef4444", lw=2.5, label="ESG–Sharpe frontier")

    ax2.scatter(esg_t,  sharpe_t,  marker="*", s=220, color="#64748b",
                edgecolors="white", linewidths=0.8, zorder=5,
                label="Optimal (unconstrained)")
    ax2.scatter(esg_te, sharpe_te, marker="*", s=220, color="#16a34a",
                edgecolors="white", linewidths=0.8, zorder=6,
                label="Optimal (ESG)")

    ax2.annotate("Unconstrained", (esg_t,  sharpe_t),
                 xytext=(-6, -16), textcoords="offset points",
                 fontsize=8, color="#64748b")
    ax2.annotate("ESG optimal",   (esg_te, sharpe_te),
                 xytext=(8, 6),   textcoords="offset points",
                 fontsize=8, color="#16a34a")

    ax2.axvline(esg_threshold, color="#f59e0b", lw=1.5, linestyle=":",
                label=f"ESG threshold ({esg_threshold:.1f})")

    ax2.set_xlabel("Portfolio ESG Score (0–100)", fontsize=11)
    ax2.set_ylabel("Sharpe Ratio",                fontsize=11)
    ax2.set_title("ESG–Sharpe Ratio Frontier",    fontsize=13, fontweight="bold",
                  color="#0d1f0f")
    ax2.legend(fontsize=7.5)
    plt.tight_layout()
    st.pyplot(fig2)
    st.caption(
        "Shows how Sharpe ratio varies as the portfolio's ESG score changes. "
        "The amber dotted line marks your minimum ESG threshold."
    )

# ──────────────────────────────────────────────────────────
# FOOTER
# ──────────────────────────────────────────────────────────
st.markdown("<br><br>", unsafe_allow_html=True)
st.markdown("""
<div style="text-align:center;font-size:12px;color:#94a3b8;padding:16px 0;">
  EcoVest · Sustainable Finance Portfolio Tool ·
  For illustrative purposes only — not financial advice.
</div>
""", unsafe_allow_html=True)