# -*- coding: utf-8 -*-
"""Sustainable

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bF9tsYmoH-l9XN4Mf7JT9-fc8UFm_AVo
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

st.set_page_config(page_title="Sustainable Finance Tool")

# =========================
# SESSION STATE
# =========================
if "step" not in st.session_state:
    st.session_state.step = 1

# =========================
# HELPER FUNCTIONS (UNCHANGED LOGIC)
# =========================

def convert_to_100(score, agency):
    agency = agency.lower()

    if agency == "sustainalytics":
        score = float(score)
        if score >= 50:
            return 0.0
        return 100 - (score / 50) * 100

    elif agency == "msci":
        msci_map = {
            "ccc": 0.0, "b": 16.7, "bb": 33.4,
            "bbb": 50.1, "a": 66.8, "aa": 83.5, "aaa": 100.0
        }
        return msci_map[str(score).lower()]

    elif agency == "refinitiv":
        ref_map = {0:0,1:10,2:25,3:50,4:75,5:95}
        return ref_map[int(score)]

    elif agency == "s&p":
        return float(score)

def portfolio_return(w, r1, r2):
    return w*r1 + (1-w)*r2

def portfolio_sd(w, sd1, sd2, rho):
    return np.sqrt(w**2*sd1**2 + (1-w)**2*sd2**2 + 2*rho*w*(1-w)*sd1*sd2)

def portfolio_esg(w, e1, e2):
    return w*e1 + (1-w)*e2

# =========================
# STEP 1: ESG METHOD
# =========================
if st.session_state.step == 1:
    st.title("Sustainable Finance Portfolio Tool")

    method = st.radio("ESG Input Method",
                      ["Overall ESG score", "Separate E, S, G scores"])

    if st.button("Next"):
        st.session_state.method = method
        st.session_state.step = 2

# =========================
# STEP 2: ASSETS
# =========================
elif st.session_state.step == 2:
    st.header("Assets")

    a1 = st.text_input("Asset 1 Name")
    a2 = st.text_input("Asset 2 Name")

    r1 = st.number_input("Return 1 (%)")/100
    r2 = st.number_input("Return 2 (%)")/100
    sd1 = st.number_input("Volatility 1 (%)")/100
    sd2 = st.number_input("Volatility 2 (%)")/100

    if st.button("Next"):
        st.session_state.a1, st.session_state.a2 = a1, a2
        st.session_state.r1, st.session_state.r2 = r1, r2
        st.session_state.sd1, st.session_state.sd2 = sd1, sd2
        st.session_state.step = 3

# =========================
# STEP 3: MARKET
# =========================
elif st.session_state.step == 3:
    rho = st.slider("Correlation", -1.0, 1.0, 0.0)
    r_free = st.number_input("Risk-free (%)")/100

    if st.button("Next"):
        st.session_state.rho = rho
        st.session_state.r_free = r_free
        st.session_state.step = 4

# =========================
# STEP 4: ESG INPUT
# =========================
elif st.session_state.step == 4:
    st.header("ESG Scores")

    agency = st.selectbox("Select ESG Agency",
                          ["sustainalytics", "refinitiv", "msci", "s&p"])

    if st.session_state.method == "Separate E, S, G scores":
        e1 = convert_to_100(st.text_input("Asset1 E"), agency)
        s1 = convert_to_100(st.text_input("Asset1 S"), agency)
        g1 = convert_to_100(st.text_input("Asset1 G"), agency)

        e2 = convert_to_100(st.text_input("Asset2 E"), agency)
        s2 = convert_to_100(st.text_input("Asset2 S"), agency)
        g2 = convert_to_100(st.text_input("Asset2 G"), agency)

        esg1 = (e1 + s1 + g1)/3
        esg2 = (e2 + s2 + g2)/3
    else:
        esg1 = convert_to_100(st.text_input("Asset1 ESG"), agency)
        esg2 = convert_to_100(st.text_input("Asset2 ESG"), agency)

    if st.button("Next"):
        st.session_state.esg1, st.session_state.esg2 = esg1, esg2
        st.session_state.step = 5

# =========================
# STEP 5: GAMMA QUESTIONNAIRE
# =========================
elif st.session_state.step == 5:
    st.header("Risk Questionnaire")

    q1 = st.slider("Risk attitude (1 cautious → 5 risk-taking)",1,5)
    q2 = st.slider("Prefer safe returns",1,5)
    q3 = st.slider("Reaction to loss",1,5)
    q4 = st.slider("High-risk allocation",1,5)
    q5 = st.slider("Prefer certain gains",1,5)

    if st.button("Calculate Gamma"):
        avg = (q1+q2+q3+q4+q5)/5

        if avg <=1.5: gamma=8
        elif avg<=2.3: gamma=4
        elif avg<=3.2: gamma=0
        elif avg<=4.1: gamma=-4
        else: gamma=-8

        st.session_state.gamma = gamma
        st.success(f"Gamma = {gamma}")
        st.session_state.step = 6

# =========================
# STEP 6: RESULTS
# =========================
elif st.session_state.step == 6:

    st.header("Results")

    r1,r2 = st.session_state.r1, st.session_state.r2
    sd1,sd2 = st.session_state.sd1, st.session_state.sd2
    rho = st.session_state.rho
    r_free = st.session_state.r_free
    esg1,esg2 = st.session_state.esg1, st.session_state.esg2
    gamma = st.session_state.gamma

    lambda_esg = st.slider("ESG Preference",0.0,1.0,0.5)

    weights = np.linspace(0,1,200)

    returns, risks, esg_vals, sharpe = [],[],[],[]
    util_esg, util_no = [],[]

    for w in weights:
        ret = portfolio_return(w,r1,r2)
        sd = portfolio_sd(w,sd1,sd2,rho)
        esg = portfolio_esg(w,esg1,esg2)

        returns.append(ret)
        risks.append(sd)
        esg_vals.append(esg)

        s = (ret-r_free)/sd if sd>0 else -np.inf
        sharpe.append(s)

        util_esg.append(ret-(gamma/2)*sd**2 + lambda_esg*(esg/100))
        util_no.append(ret-(gamma/2)*sd**2)

    i = np.argmax(sharpe)

    st.write("Tangency weights:", weights[i], 1-weights[i])

    fig, ax = plt.subplots()
    sc = ax.scatter(risks, returns, c=esg_vals, cmap="YlGn")
    plt.colorbar(sc, ax=ax)
    st.pyplot(fig)