# -*- coding: utf-8 -*-
"""Sustainable gpt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bF9tsYmoH-l9XN4Mf7JT9-fc8UFm_AVo
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.ticker import PercentFormatter

st.set_page_config(layout="wide")

# ==========================================================
# ORIGINAL FUNCTIONS (UNCHANGED)
# ==========================================================

def convert_to_100(score, agency):
    agency = agency.lower()

    if agency == "sustainalytics":
        score = float(score)
        if score >= 50:
            return 0.0
        converted = 100 - (score / 50) * 100
        return max(0.0, min(100.0, converted))

    elif agency == "msci":
        msci_map = {
            "ccc": 0.0, "b": 16.7, "bb": 33.4,
            "bbb": 50.1, "a": 66.8, "aa": 83.5, "aaa": 100.0
        }
        score = str(score).strip().lower()
        if score not in msci_map:
            raise ValueError("Invalid MSCI rating")
        return msci_map[score]

    elif agency == "refinitiv":
        score = int(float(score))
        refinitiv_map = {
            0: 0.0, 1: 10.0, 2: 25.0,
            3: 50.0, 4: 75.0, 5: 95.0
        }
        if score not in refinitiv_map:
            raise ValueError("Invalid Refinitiv / LSEG score")
        return refinitiv_map[score]

    elif agency == "s&p":
        score = float(score)
        return max(0.0, min(100.0, score))

    else:
        raise ValueError("Unknown agency.")


def convert_100_to_1(score_100):
    return score_100 / 100


def portfolio_return(w1, r1, r2):
    return w1 * r1 + (1 - w1) * r2


def portfolio_sd(w1, sd1, sd2, rho):
    return np.sqrt(
        w1 ** 2 * sd1 ** 2 +
        (1 - w1) ** 2 * sd2 ** 2 +
        2 * rho * w1 * (1 - w1) * sd1 * sd2
    )


def portfolio_esg(w1, esg1, esg2):
    return w1 * esg1 + (1 - w1) * esg2


def get_esg_threshold(lambda_esg, esg1_100, esg2_100):
    esg_min = min(esg1_100, esg2_100)
    esg_max = max(esg1_100, esg2_100)
    return esg_min + lambda_esg * (esg_max - esg_min)


# ==========================================================
# SIDEBAR INPUTS (UI VERSION OF ORIGINAL FLOW)
# ==========================================================

st.sidebar.title("Portfolio Inputs")

# ESG METHOD
esg_input_method = st.sidebar.radio(
    "ESG Input Method",
    ["Overall ESG score", "Separate E, S, G scores"]
)
use_separate_scores = (esg_input_method == "Separate E, S, G scores")

pillar_weights = None
if use_separate_scores:
    w_e = st.sidebar.number_input("Environmental weight (%)", 0.0, 100.0, 33.0)
    w_s = st.sidebar.number_input("Social weight (%)", 0.0, 100.0, 33.0)
    w_g = st.sidebar.number_input("Governance weight (%)", 0.0, 100.0, 34.0)
    pillar_weights = (w_e, w_s, w_g)

# ASSETS
asset1_name = st.sidebar.text_input("Asset 1 name")
asset2_name = st.sidebar.text_input("Asset 2 name")

r1 = st.sidebar.number_input("Asset 1 return (%)") / 100
sd1 = st.sidebar.number_input("Asset 1 volatility (%)", min_value=0.0) / 100

r2 = st.sidebar.number_input("Asset 2 return (%)") / 100
sd2 = st.sidebar.number_input("Asset 2 volatility (%)", min_value=0.0) / 100

# MARKET
rho = st.sidebar.slider("Correlation", -1.0, 1.0, 0.0)
r_free = st.sidebar.number_input("Risk-free rate (%)") / 100

# GAMMA
gamma_input = st.sidebar.text_input("Gamma (or type 'not sure')")

if gamma_input.lower() == "not sure":
    scores = []
    scores.append(st.sidebar.slider("Q1", 1, 5))
    scores.append(st.sidebar.slider("Q2", 1, 5))
    scores.append(st.sidebar.slider("Q3", 1, 5))
    scores.append(st.sidebar.slider("Q4", 1, 5))
    scores.append(st.sidebar.slider("Q5", 1, 5))

    avg = sum(scores) / len(scores)

    if avg <= 1.5:
        gamma = 8
    elif avg <= 2.3:
        gamma = 4
    elif avg <= 3.2:
        gamma = 0
    elif avg <= 4.1:
        gamma = -4
    else:
        gamma = -8
else:
    gamma = float(gamma_input) if gamma_input else 0

# ESG SCORES
agency1 = st.sidebar.selectbox("Agency Asset 1", ["sustainalytics","refinitiv","msci","s&p"])
agency2 = st.sidebar.selectbox("Agency Asset 2", ["sustainalytics","refinitiv","msci","s&p"])

def get_esg(asset, agency):
    if use_separate_scores:
        e = convert_to_100(st.sidebar.text_input(f"{asset} E"), agency)
        s = convert_to_100(st.sidebar.text_input(f"{asset} S"), agency)
        g = convert_to_100(st.sidebar.text_input(f"{asset} G"), agency)

        w_e, w_s, w_g = pillar_weights
        return (w_e/100)*e + (w_s/100)*s + (w_g/100)*g

    else:
        return convert_to_100(st.sidebar.text_input(f"{asset} ESG"), agency)

esg1_100 = get_esg(asset1_name, agency1)
esg2_100 = get_esg(asset2_name, agency2)

esg1_1 = convert_100_to_1(esg1_100)
esg2_1 = convert_100_to_1(esg2_100)

# ESG PREFERENCE
lambda_esg = st.sidebar.selectbox("Lambda", [0.0,0.25,0.75,1.0])

# ==========================================================
# CALCULATIONS (UNCHANGED)
# ==========================================================

weights = np.linspace(0, 1, 1000)

returns, risks, esg_scores_100, sharpe_ratios = [],[],[],[]

for w in weights:
    port_ret = portfolio_return(w, r1, r2)
    port_sd = portfolio_sd(w, sd1, sd2, rho)
    port_esg = portfolio_esg(w, esg1_100, esg2_100)

    returns.append(port_ret)
    risks.append(port_sd)
    esg_scores_100.append(port_esg)

    sharpe_ratios.append((port_ret - r_free) / port_sd if port_sd > 0 else -np.inf)

# Tangency
i = np.argmax(sharpe_ratios)

w1_tangency = weights[i]
ret_tangency = returns[i]
sd_tangency = risks[i]
esg_tangency_100 = esg_scores_100[i]

# ESG constraint
esg_threshold = get_esg_threshold(lambda_esg, esg1_100, esg2_100)

eligible = [i for i in range(len(weights)) if esg_scores_100[i] >= esg_threshold]

i_esg = max(eligible, key=lambda i: sharpe_ratios[i])

w1_tangency_esg = weights[i_esg]
ret_tangency_esg = returns[i_esg]
sd_tangency_esg = risks[i_esg]
esg_tangency_esg_100 = esg_scores_100[i_esg]

# ==========================================================
# MAIN DISPLAY
# ==========================================================

st.title("ESG Optimal Portfolio")

# Allocation bars
col1, col2 = st.columns(2)

with col1:
    st.subheader("No ESG Constraint")
    st.bar_chart(pd.DataFrame(
        [w1_tangency, 1 - w1_tangency],
        index=[asset1_name, asset2_name]
    ))

with col2:
    st.subheader("With ESG Constraint")
    st.bar_chart(pd.DataFrame(
        [w1_tangency_esg, 1 - w1_tangency_esg],
        index=[asset1_name, asset2_name]
    ))

# ESG ring
color = f"hsl({int(esg_tangency_esg_100)}, 100%, 50%)"

st.markdown(f"""
<div style="text-align:center;">
<div style="width:160px;height:160px;border-radius:50%;
background:conic-gradient({color} {esg_tangency_esg_100}%, #ccc {esg_tangency_esg_100}%);">
</div>
<p style="font-size:24px">{esg_tangency_esg_100:.2f}</p>
</div>
""", unsafe_allow_html=True)

# Tables
portfolio_table = pd.DataFrame({
    "Metric": ["Return","Risk","ESG","Sharpe"],
    "No ESG": [ret_tangency, sd_tangency, esg_tangency_100, sharpe_ratios[i]],
    "With ESG": [ret_tangency_esg, sd_tangency_esg, esg_tangency_esg_100, sharpe_ratios[i_esg]]
})

st.dataframe(portfolio_table)

# Frontier chart (UNCHANGED)
fig, ax = plt.subplots()

ax.plot(risks, returns)
ax.scatter(sd_tangency, ret_tangency, marker="*")
ax.scatter(sd_tangency_esg, ret_tangency_esg, marker="*")

ax.xaxis.set_major_formatter(PercentFormatter(1.0))
ax.yaxis.set_major_formatter(PercentFormatter(1.0))

st.pyplot(fig)